### ISSUE TITLE
Command failed: git checkout add-devnet-quorum

### ISSUE THREAD

**Issue by ryansd92** [dashpay/insight-api#69]
It appears the latest update broke the install. See my command output below.

Specifically: **error: pathspec 'add-devnet-quorum' did not match any file(s) known to git.**

```
ubuntu@fe4eacf6771c:~/mynode$ dashcore-node install @dashevo/insight-api
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! Command failed: git checkout add-devnet-quorum
npm ERR! error: pathspec 'add-devnet-quorum' did not match any file(s) known to git.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-10-26T16_54_46_126Z-debug.log
/home/ubuntu/.nvm/versions/node/v12.19.0/lib/node_modules/@dashevo/dashcore-node/lib/cli/main.js:87
          throw err;
          ^

Error: There was an error installing service: @dashevo/insight-api
    at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.19.0/lib/node_modules/@dashevo/dashcore-node/lib/scaffold/add.js:56:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by ryansd92** [comment]
Looks like this branch is no longer there. https://github.com/dashevo/insight-api/blob/3a938c417225b0c1d03549971b157a2c53ea0fe4/package.json#L63

**Comment by shumkov** [comment]
Hello!

Thank you for the report.

Yeah, it seems it’s merged and was deleted. Please try to use dashcore-lib 0.18.14 in package.json instead of the branch.
